// SPDX-License-Identifier: MPL-2.0
/** Canvas type handles preview a pinned axis or an explicit text-and-frame scale. */
import { textStyleResolver,formatStoryRange,formatStoryParagraphs,scaleTextStory,scaleTextFrame,parseTextDocument } from '@lolly/engine';
import type { TextRangeV1,TextFontInfoV1 } from '@lolly-tools/core';
import type { HostV1 } from '@lolly-tools/core/host-v1';
import { textControlNumber, styleTextControls } from '../../lib/text-control-ui.ts';
import { t } from '../../i18n.ts';
import { announce } from '../../a11y.ts';
import { bindOp,type FcCtx } from './context.ts';
export async function open(fc:FcCtx,anchor:HTMLElement,id:string,range?:TextRangeV1,scaleMode=false):Promise<void>{
  try{
    const anchorRect=anchor.getBoundingClientRect();if(fc.editing?.composed){await fc.editing.composed.editor.settle();await fc.storyText.finish();}fc.toolbox.closePopover();
    let snapshot=fc.storyText.read(),key=JSON.stringify(snapshot),frame=snapshot.frames.find(frame=>frame.id===id);if(!frame||frame.locked)return;
    const storyId=frame.storyId,current=()=>snapshot.document.stories.find(story=>story.id===storyId)!,selected=range&&range.start!==range.end?range:{start:0,end:current().source.length};
    if(scaleMode&&current().frameIds.length!==1)throw new Error(t('Scale text and frame needs a standalone story.'));
    const resolve=()=>{const story=current(),paragraph=story.paragraphs.find(paragraph=>paragraph.start<=selected.start&&paragraph.end>=selected.start)??story.paragraphs[0]!;return textStyleResolver(snapshot.document).character(story,paragraph,selected.start);};
    let info:TextFontInfoV1|undefined;
    if(!scaleMode){const font=snapshot.document.fonts.find(font=>font.id===resolve().font),api=(fc.host as HostV1).text;if(!font||!api?.fontInfo)throw new Error(t('Font metadata is unavailable.'));info=await api.fontInfo(font);if(JSON.stringify(fc.storyText.read())!==key)throw new Error(t('The story changed. Reopen its type controls.'));if(!Object.keys(info.axes).length)throw new Error(t('This font has no variable axes.'));}
    const panel=document.createElement('div');panel.className='fc-text-popover';panel.dataset.textTypeAdjust='';panel.setAttribute('role','dialog');panel.setAttribute('aria-label',scaleMode?t('Scale text and frame'):t('Adjust type'));panel.setAttribute('data-export-hide','');fc.popover=panel;fc.popoverAnchor=anchor;fc.rail.hideCtxBar();
    const caption=document.createElement('p');caption.textContent=scaleMode?t('Scale the complete standalone story and its frame.'):range?t('Selected text'):t('Entire selected story');panel.append(caption);
    const select=document.createElement('select');select.setAttribute('aria-label',t('Font axis'));for(const [tag,axis] of Object.entries(info?.axes??{}))select.add(new Option(axis.name,tag));if(!scaleMode)panel.append(select);
    const numeric=textControlNumber(panel,scaleMode?t('Text and frame scale (%)'):t('Font axis value'),{value:100,step:1,precision:2,onCommit:value=>{draft=clamp(value);void commit();}}),field=numeric.input;
    const status=document.createElement('p');status.setAttribute('role','status');status.textContent=t('Drag the handle or use arrow keys. Enter commits; Escape cancels.');panel.append(status);
    const handle=document.createElement('button');handle.type='button';handle.className='fc-text-flow-port';handle.dataset.textTypeHandle='';handle.style.touchAction='none';handle.style.minWidth='44px';fc.overlay.append(handle);
    const line=document.createElement('div');line.setAttribute('aria-hidden','true');line.dataset.textTypeGuide='';Object.assign(line.style,{position:'absolute',height:'2px',background:'currentColor',pointerEvents:'none'});fc.overlay.append(line);
    let closed=false,ticket=0,raf=0,draft=100,drag:{x:number;value:number}|undefined,moved=false;const saved=new Map<string,string>();
    const target=(frameId:string)=>fc.stage.liveBoxEl(frameId)?.querySelector<HTMLElement>('.lolly-box-text');
    const axis=()=>scaleMode?{min:1,max:1000,default:100,name:t('Scale')}:info!.axes[select.value]!;
    const value=()=>scaleMode?100:resolve().axes?.[select.value]??(select.value==='wght'?resolve().weight:undefined)??axis().default;
    const clamp=(value:number)=>Math.max(axis().min,Math.min(axis().max,value));
    function updated(){const next=structuredClone(snapshot);if(scaleMode){next.document=scaleTextStory(next.document,storyId,draft/100);next.document.stories.find(story=>story.id===storyId)!.revision++;next.frames=next.frames.map(item=>item.id===id?scaleTextFrame(item,draft/100):item);}else{const story=current(),character={axes:{...resolve().axes,[select.value]:draft}};next.document.stories=next.document.stories.map(item=>item.id!==storyId?item:selected.start===selected.end?formatStoryParagraphs(story,story.paragraphs.map(paragraph=>paragraph.id),{character:{...resolve(),...character}}):formatStoryRange(story,selected,{character}));}next.document=parseTextDocument(next.document);return next;}
    function restore(){ticket++;if(JSON.stringify(fc.storyText.read())===key)for(const [frameId,html] of saved){const element=target(frameId);if(element)element.innerHTML=html;}saved.clear();}
    function position(){const rect=fc.stage.liveBoxEl(id)?.getBoundingClientRect(),root=fc.overlay.getBoundingClientRect();if(!rect)return;const width=Math.max(120,Math.min(260,rect.width)),left=rect.left-root.left,top=Math.max(24,rect.top-root.top-36),fraction=(draft-axis().min)/(axis().max-axis().min);line.style.left=`${left}px`;line.style.top=`${top}px`;line.style.width=`${width}px`;handle.style.left=`${left+width*fraction-22}px`;handle.style.top=`${top-22}px`;handle.textContent=`${axis().name} ${Math.round(draft*100)/100}`;handle.setAttribute('aria-label',`${axis().name}: ${Math.round(draft*100)/100}`);}
    const follow=()=>{if(closed)return;position();raf=requestAnimationFrame(follow);};
    async function preview(){const generation=++ticket;try{const next=updated(),layout=await fc.storyText.layout({document:next.document,storyId,frames:next.frames.filter(frame=>frame.storyId===storyId),includeSvg:true});if(closed||generation!==ticket||JSON.stringify(fc.storyText.read())!==key)return;for(const frame of layout.frames){const element=target(frame.id);if(element&&frame.svg){if(!saved.has(frame.id))saved.set(frame.id,element.innerHTML);element.innerHTML=frame.svg;}}status.textContent=layout.overset?t('Text continues beyond this frame.'):t('Preview only. Enter commits; Escape cancels.');}catch(error){if(generation===ticket)status.textContent=error instanceof Error?error.message:String(error);}}
    async function commit(){if(JSON.stringify(fc.storyText.read())!==key){restore();status.textContent=t('The story changed. Reopen its type controls.');return;}try{const next=updated();await fc.storyText.layout({document:next.document,storyId,frames:next.frames.filter(frame=>frame.storyId===storyId)});ticket++;await fc.storyText.write(next,scaleMode?t('Scale text and frame'):t('Adjust type'));saved.clear();if(closed)return;snapshot=fc.storyText.read();key=JSON.stringify(snapshot);frame=snapshot.frames.find(frame=>frame.id===id);draft=value();numeric.set(draft);}catch(error){restore();status.textContent=error instanceof Error?error.message:String(error);}}
    const reset=()=>{restore();draft=value();numeric.bounds(axis().min,axis().max);numeric.set(draft);position();};select.addEventListener('change',reset);
    handle.addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();drag={x:event.clientX,value:draft};moved=false;handle.setPointerCapture(event.pointerId);handle.focus();});handle.addEventListener('pointermove',event=>{if(!drag)return;const delta=event.clientX-drag.x;moved ||= Math.abs(delta)>2;draft=clamp(drag.value+delta/Math.max(1,line.getBoundingClientRect().width)*(axis().max-axis().min));numeric.set(draft);position();void preview();});handle.addEventListener('pointerup',()=>{if(!drag)return;drag=undefined;if(moved)void commit();else{field.focus();field.select();}});handle.addEventListener('pointercancel',()=>{drag=undefined;reset();});
    handle.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();drag=undefined;reset();}else if(event.key==='Enter'){event.preventDefault();void commit();}else if(event.key.startsWith('Arrow')){event.preventDefault();event.stopPropagation();draft=clamp(draft+(['ArrowLeft','ArrowDown'].includes(event.key)?-1:1)*(event.shiftKey?10:1));numeric.set(draft);position();void preview();}});
    const done=document.createElement('button');done.type='button';done.textContent=t('Done');done.addEventListener('click',()=>fc.toolbox.closePopover(true));panel.append(done);panel.addEventListener('pointerdown',event=>event.stopPropagation());panel.addEventListener('keydown',event=>{event.stopPropagation();if(event.key==='Escape'){event.preventDefault();fc.toolbox.closePopover(true);}});panel.addEventListener('lolly:popover-close',()=>{closed=true;cancelAnimationFrame(raf);restore();handle.remove();line.remove();fc.chromeSync.renderChrome();});styleTextControls(panel);document.body.append(panel);panel.style.left=`${Math.max(8,Math.min(anchorRect.left,innerWidth-panel.offsetWidth-8))}px`;panel.style.top=`${Math.max(8,Math.min(anchorRect.bottom+8,innerHeight-panel.offsetHeight-8))}px`;reset();follow();field.focus();
  }catch(error){announce(error instanceof Error?error.message:String(error));}
}
export function storyTypeOps(fc:FcCtx){return {open:bindOp(fc,open)};}
