// SPDX-License-Identifier: MPL-2.0
/** One large active guide handle has equivalent numeric and keyboard controls. */
import { textGuideGeometry, parseSvgPath } from '@lolly/engine';
import { textControlNumber, styleTextControls } from '../../lib/text-control-ui.ts';
import { t } from '../../i18n.ts';
import { bindOp, type FcCtx } from './context.ts';
type Property='start'|'end'|'baseline';
export function open(fc:FcCtx,anchor:HTMLElement,id:string,initial:Property='start'):void{
  if(fc.editing)fc.textEdit.commitTextEdit();fc.toolbox.closePopover();
  let snapshot=fc.storyText.read(),frame=snapshot.frames.find(frame=>frame.id===id),key=JSON.stringify(snapshot);if(!frame?.path||frame.locked)return;
  let path=structuredClone(frame.path),draft=structuredClone(path),ticket=0,closed=false,drag=false,moved=false,saved:string|undefined,raf=0;
  const panel=document.createElement('div');panel.className='fc-text-popover';panel.dataset.textPathAdjust='';panel.setAttribute('data-export-hide','');panel.setAttribute('role','dialog');panel.setAttribute('aria-label',t('Adjust path'));fc.popover=panel;fc.popoverAnchor=anchor;
  fc.storyPathUi.paint();
  const select=document.createElement('select');select.setAttribute('aria-label',t('Path handle'));for(const [key,label] of [['start',t('Path start')],['end',t('Path end')],['baseline',t('Baseline offset')]])select.add(new Option(label,key));
  select.value=initial;
  panel.append(select);const numeric=textControlNumber(panel,t('Path handle value'),{value:0,min:-100000,max:100000,step:1,precision:3,onCommit:value=>{draft[property()]=clamp(value);numeric.set(draft[property()]);void commit();}}),input=numeric.input;
  const status=document.createElement('p');status.setAttribute('role','status');status.textContent=t('Drag the handle or use arrow keys. Enter commits; Escape cancels.');panel.append(status);
  const handle=document.createElement('button');handle.type='button';handle.className='fc-text-flow-port';handle.dataset.textAdjust='';handle.style.touchAction='none';fc.overlay.append(handle);
  const guide=document.createElementNS('http://www.w3.org/2000/svg','svg');guide.dataset.textAdjust='';guide.setAttribute('aria-hidden','true');Object.assign(guide.style,{position:'absolute',inset:'0',width:'100%',height:'100%',overflow:'visible',pointerEvents:'none'});fc.overlay.append(guide);
  const target=()=>fc.stage.liveBoxEl(id)?.querySelector<HTMLElement>('.lolly-box-text');
  const property=()=>select.value as Property,geometry=textGuideGeometry(path.d),isClosed=!!parseSvgPath(path.d)[0]?.closed;
  const clamp=(value:number)=>property()==='baseline'?Math.max(-100000,Math.min(100000,value)):property()==='start'?Math.max(0,Math.min(geometry.length-.001,draft.end-.001,value)):Math.max(draft.start+.001,Math.min(isClosed?draft.start+geometry.length:geometry.length,value));
  function sample(distance:number){let d=draft.flip?draft.start+draft.end-distance:distance;d=draft.reverse?geometry.length-d:d;if(isClosed)d=((d%geometry.length)+geometry.length)%geometry.length;const at=geometry.at(d);return {...at,angle:at.angle+(draft.reverse?180:0)+(draft.flip?180:0)};}
  function location(){const at=sample(property()==='start'?draft.start:property()==='end'?draft.end:(draft.start+draft.end)/2),angle=at.angle*Math.PI/180;return {...at,x:at.x-Math.sin(angle)*draft.baseline,y:at.y+Math.cos(angle)*draft.baseline};}
  function position(){
    const svg=target()?.querySelector('svg'),matrix=svg?.getScreenCTM();if(!matrix)return;
    const root=fc.overlay.getBoundingClientRect(),at=location(),p=new DOMPoint(at.x,at.y).matrixTransform(matrix);
    handle.style.left=`${p.x-root.x-22}px`;handle.style.top=`${p.y-root.y-22}px`;handle.textContent=String(Math.round(draft[property()]*10)/10);handle.setAttribute('aria-label',`${select.selectedOptions[0]?.text}: ${handle.textContent}`);
    const d=path.d.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');guide.innerHTML=`<g transform="matrix(${matrix.a} ${matrix.b} ${matrix.c} ${matrix.d} ${matrix.e-root.x} ${matrix.f-root.y})"><path d="${d}" fill="none" stroke="currentColor" stroke-width="1" vector-effect="non-scaling-stroke" stroke-dasharray="4 3"/></g>`;
  }
  const loop=()=>{if(closed)return;position();raf=requestAnimationFrame(loop);};
  function restore(){ticket++;if(saved!==undefined&&JSON.stringify(fc.storyText.read())===key){const element=target();if(element)element.innerHTML=saved;}saved=undefined;}
  async function preview(){const generation=++ticket;try{const next=structuredClone(snapshot);next.frames=next.frames.map(frame=>frame.id===id?{...frame,path:structuredClone(draft)}:frame);const layout=await fc.storyText.layout({document:next.document,storyId:frame!.storyId,frames:next.frames.filter(item=>item.storyId===frame!.storyId),includeSvg:true});if(closed||generation!==ticket||JSON.stringify(fc.storyText.read())!==key)return;const element=target(),svg=layout.frames[0]?.svg;if(element&&svg){saved??=element.innerHTML;element.innerHTML=svg;}status.textContent=layout.overset?t('Text continues beyond the path endpoint.'):t('All story text fits.');}catch(error){if(generation===ticket)status.textContent=error instanceof Error?error.message:String(error);}}
  async function commit(){if(JSON.stringify(fc.storyText.read())!==key){restore();status.textContent=t('The text changed. Reopen its path controls.');return;}try{ticket++;await fc.storyPath.update(id,{path:structuredClone(draft)},t('Adjust text path'));saved=undefined;if(closed)return;snapshot=fc.storyText.read();key=JSON.stringify(snapshot);frame=snapshot.frames.find(frame=>frame.id===id);path=structuredClone(frame!.path!);draft=structuredClone(path);numeric.set(draft[property()]);}catch(error){restore();status.textContent=error instanceof Error?error.message:String(error);}}
  const reset=()=>{restore();draft=structuredClone(path);numeric.bounds(property()==='baseline'?-100000:property()==='end'?draft.start+.001:0,property()==='baseline'?100000:property()==='start'?Math.min(geometry.length-.001,draft.end-.001):isClosed?draft.start+geometry.length:geometry.length);numeric.set(draft[property()]);position();};select.addEventListener('change',reset);

  handle.addEventListener('pointerdown',event=>{event.preventDefault();event.stopPropagation();drag=true;moved=false;handle.setPointerCapture(event.pointerId);handle.focus();});
  handle.addEventListener('pointermove',event=>{if(!drag)return;const matrix=target()?.querySelector('svg')?.getScreenCTM();if(!matrix)return;const point=new DOMPoint(event.clientX,event.clientY).matrixTransform(matrix.inverse());let value=draft[property()];if(property()==='baseline'){const at=sample((draft.start+draft.end)/2),angle=at.angle*Math.PI/180;value=-(point.x-at.x)*Math.sin(angle)+(point.y-at.y)*Math.cos(angle);}else{let best=Infinity,bestD=0;for(let i=0;i<=512;i++){const distance=geometry.length*i/512,at=geometry.at(distance),cost=(at.x-point.x)**2+(at.y-point.y)**2;if(cost<best){best=cost;bestD=distance;}}let lo=Math.max(0,bestD-geometry.length/512),hi=Math.min(geometry.length,bestD+geometry.length/512);const cost=(d:number)=>{const at=geometry.at(d);return (at.x-point.x)**2+(at.y-point.y)**2;};for(let i=0;i<16;i++){const a=lo+(hi-lo)/3,b=hi-(hi-lo)/3;if(cost(a)<cost(b))hi=b;else lo=a;}let distance=(lo+hi)/2;if(draft.reverse)distance=geometry.length-distance;if(draft.flip)distance=draft.start+draft.end-distance;if(isClosed)distance+=[-geometry.length,0,geometry.length].sort((a,b)=>Math.abs(distance+a-value)-Math.abs(distance+b-value))[0]!;value=distance;}
    value=clamp(value);if(Math.abs(value-draft[property()])>.01)moved=true;draft[property()]=Math.round(value*1000)/1000;numeric.set(draft[property()]);position();void preview();});
  handle.addEventListener('pointerup',()=>{if(!drag)return;drag=false;if(moved)void commit();else{input.focus();input.select();}});handle.addEventListener('pointercancel',()=>{drag=false;reset();});
  handle.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();drag=false;reset();}else if(event.key==='Enter'){event.preventDefault();void commit();}else if(event.key.startsWith('Arrow')){event.preventDefault();event.stopPropagation();draft[property()]=clamp(draft[property()]+(['ArrowLeft','ArrowUp'].includes(event.key)?-1:1)*(event.shiftKey?10:1));numeric.set(draft[property()]);position();void preview();}});
  panel.addEventListener('pointerdown',event=>event.stopPropagation());panel.addEventListener('keydown',event=>{event.stopPropagation();if(event.key==='Escape'){event.preventDefault();fc.toolbox.closePopover(true);}});
  panel.addEventListener('lolly:popover-close',()=>{closed=true;cancelAnimationFrame(raf);restore();guide.remove();handle.remove();queueMicrotask(()=>fc.storyPathUi.paint());});const done=document.createElement('button');done.type='button';done.textContent=t('Done');done.addEventListener('click',()=>fc.toolbox.closePopover(true));panel.append(done);
  styleTextControls(panel);document.body.append(panel);const rect=anchor.getBoundingClientRect();panel.style.left=`${Math.max(8,Math.min(rect.left,innerWidth-panel.offsetWidth-8))}px`;panel.style.top=`${Math.max(8,Math.min(rect.bottom+8,innerHeight-panel.offsetHeight-8))}px`;reset();loop();select.focus();
}
export function storyPathHandlesOps(fc:FcCtx){return {open:bindOp(fc,open)};}
