// SPDX-License-Identifier: MPL-2.0

const COMMANDS: &[&str] = &["authenticate", "google_authorize"];

fn main() {
    // Writes the per-command permissions under permissions/autogenerated, sets
    // the `mobile` and `desktop` cfg flags, and, when building for a phone,
    // copies the Tauri native API next to the plugin and compiles the Swift
    // package (iOS) or registers the Gradle module (Android).
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
