// SPDX-License-Identifier: MPL-2.0
/** Portable Node worker: deploy beside the pinned WASM, independent of TS loaders. */
import { build } from 'esbuild';
await build({ entryPoints: ['packages/node-shell/src/jxl-worker.ts'], outfile: 'packages/node-shell/wasm/jxl/vendor/worker.mjs', bundle: true, platform: 'node', format: 'esm', target: 'node24', minify: true, banner: { js: '// Generated by scripts/build-jxl-worker.ts. MPL-2.0 adapter; embedded libjxl glue licenses are adjacent.' } });
